import time
import requests
from bs4 import BeautifulSoup
import csv
import datetime
from selenium import webdriver
from selenium.webdriver.chrome.service import Service


# ПЕРЕПИСАТЬ ССЫЛКИ


now = datetime.datetime.now()
date = now.strftime("%d-%m-%Y")

url = "https://social-apteka.ru/catalog/"
HEADERS = {
    "Accept": "*/*",
    "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:93.0) Gecko/20100101 Firefox/93.0"
}

name = "Социальная аптека"

# citys = ['https://astrahan.', 'https://belgorod.', 'https://volgograd.', 'https://voronezh.', 'https://krasnodar.', 'https://lipeck.', 'https://majkop.', 'https://', 'https://stavropol.',
linklist = [
    "https://astrahan.social-apteka.ru/catalog/bolezni-sustavov/ameloteks-r-r-d-in-1-5ml-n5-soteks_33449/",
    "https://astrahan.social-apteka.ru/catalog/bolezni-sustavov/armaviskon-r-r-dvnutrisust-vved-2ml-2_1549818/",
    "https://astrahan.social-apteka.ru/catalog/bolezni-sustavov/armaviskon-plyus-r-r-dvnutrisust-vved-2ml-86_1549819/",
    "https://astrahan.social-apteka.ru/catalog/bolezni-sustavov/armaviskon-forte-r-r-dvnutrisust-vved-shpric-3ml-53_29463/",
    "https://astrahan.social-apteka.ru/catalog/kat/armaviskon-hondro-protez-sinovialnoy-jidkosti-3ml-n1-groteks-7_34113316/",
    "https://astrahan.social-apteka.ru/catalog/bolezni-sustavov/artogistan-r-r-din-100mgml-2ml-n10-41_28657/",
    "https://astrahan.social-apteka.ru/catalog/bolezni-sustavov/genitron-r-r-din-10mgml-15ml-n5-74_27287/",
    "https://astrahan.social-apteka.ru/catalog/bolezni-sustavov/gialurom-r-r-vsustav-shpric-15-2ml-n1-90_38239/",
    "https://astrahan.social-apteka.ru/catalog/bolezni-sustavov/gialurom-cs-vsustav-shpric-15-3ml-n1-10_23499/",
    "https://astrahan.social-apteka.ru/search_to_go/?q=%D0%94%D1%8C%D1%8E%D1%80%D0%B0%D0%BB%D0%B0%D0%BD",
    "https://astrahan.social-apteka.ru/catalog/bolezni-sustavov/inektran-r-r-din-100mgml-2ml-n10-95_27204/",
    "https://astrahan.social-apteka.ru/catalog/protivovospalitelnye-sredstva-dlya-oporno-dvigatelnogo-apparata/meloksikam-r-r-din-10mgml-15ml-n5-100_8389805/",
    "https://astrahan.social-apteka.ru/catalog/obezbolivayushchie/movalis-amp-15mg-15ml-n5-67_20078/",
    "https://astrahan.social-apteka.ru/catalog/bolezni-sustavov/mukosat-amp-10-1ml-n10-84_16578/",
    "https://astrahan.social-apteka.ru/catalog/kat/osteokoll-implantat-kollagen-d-periartikulyarnogo-vved-2ml-n5-guna-70_34085377/",
    "https://astrahan.social-apteka.ru/catalog/kat/pleksatron-kollagen-dvnutrisustav-i-periart-vved-2ml-n5-guna-96_34077275/",
    "https://astrahan.social-apteka.ru/catalog/kat/ripart-long-sr-vo-dzameshch-sinov-jidk-20mgml-2ml-shpric-n1-ingal-70_32534640/",
    "https://astrahan.social-apteka.ru/catalog/bolezni-sustavov/ripart-long-sr-vo-dzameshch-sinovialnoy-jidkosti-20mgml-shpric-3ml-n1-rossiya-18_71697/",
    "https://astrahan.social-apteka.ru/catalog/kat/ripart-forte-sr-vo-dlya-zameshcheniya-sinovialnoy-jidkosti-15mgml-shpric-3ml-100_34077342/",
    "https://astrahan.social-apteka.ru/catalog/bolezni-sustavov/rumalon-amp-1ml-n10-39_24853/",
    "https://astrahan.social-apteka.ru/catalog/gomeopatiya/traumel-s-amp-22ml-n5-44_11979/",
    "https://astrahan.social-apteka.ru/catalog/bolezni-sustavov/fermatron-shpric-1-2ml-n1-77_33430/",
    "https://astrahan.social-apteka.ru/catalog/bolezni-sustavov/fermatron-shpric-15-2ml-n1-38_34995/",
    "https://astrahan.social-apteka.ru/catalog/kat/fleksotron-kross-implantant-din-60mg3ml-sayvijn-bayotek-6_32534636/",
    "https://astrahan.social-apteka.ru/catalog/kat/fleksotron-solo-implant-din-22-22mgml-2ml-sistema-plyus-20_33579271/",
    "https://astrahan.social-apteka.ru/catalog/kat/fleksotron-ultra-implant-din-25-25mgml-48ml-albomed-63_33593771/",
    "https://astrahan.social-apteka.ru/catalog/kat/hronotron-implantat-inekc-gel-dlya-vsust-vved-20mgml-2ml-n1-mastelli-61_33593758/",
    "https://belgorod.social-apteka.ru/catalog/bolezni-sustavov/ameloteks-r-r-d-in-1-5ml-n5-soteks_33449/",
    "https://belgorod.social-apteka.ru/catalog/bolezni-sustavov/armaviskon-r-r-dvnutrisust-vved-2ml-2_1549818/",
    "https://belgorod.social-apteka.ru/catalog/bolezni-sustavov/armaviskon-plyus-r-r-dvnutrisust-vved-2ml-86_1549819/",
    "https://belgorod.social-apteka.ru/catalog/bolezni-sustavov/armaviskon-forte-r-r-dvnutrisust-vved-shpric-3ml-53_29463/",
    "https://belgorod.social-apteka.ru/catalog/kat/armaviskon-hondro-protez-sinovialnoy-jidkosti-3ml-n1-groteks-7_34113316/",
    "https://belgorod.social-apteka.ru/catalog/bolezni-sustavov/artogistan-r-r-din-100mgml-2ml-n10-41_28657/",
    "https://belgorod.social-apteka.ru/catalog/bolezni-sustavov/genitron-r-r-din-10mgml-15ml-n5-74_27287/",
    "https://belgorod.social-apteka.ru/catalog/bolezni-sustavov/gialurom-r-r-vsustav-shpric-15-2ml-n1-90_38239/",
    "https://belgorod.social-apteka.ru/catalog/bolezni-sustavov/gialurom-cs-vsustav-shpric-15-3ml-n1-10_23499/",
    "https://belgorod.social-apteka.ru/search_to_go/?q=%D0%94%D1%8C%D1%8E%D1%80%D0%B0%D0%BB%D0%B0%D0%BD",
    "https://belgorod.social-apteka.ru/catalog/bolezni-sustavov/inektran-r-r-din-100mgml-2ml-n10-95_27204/",
    "https://belgorod.social-apteka.ru/catalog/protivovospalitelnye-sredstva-dlya-oporno-dvigatelnogo-apparata/meloksikam-r-r-din-10mgml-15ml-n5-100_8389805/",
    "https://belgorod.social-apteka.ru/catalog/obezbolivayushchie/movalis-amp-15mg-15ml-n5-67_20078/",
    "https://belgorod.social-apteka.ru/catalog/bolezni-sustavov/mukosat-amp-10-1ml-n10-84_16578/",
    "https://belgorod.social-apteka.ru/catalog/kat/osteokoll-implantat-kollagen-d-periartikulyarnogo-vved-2ml-n5-guna-70_34085377/",
    "https://belgorod.social-apteka.ru/catalog/kat/pleksatron-kollagen-dvnutrisustav-i-periart-vved-2ml-n5-guna-96_34077275/",
    "https://belgorod.social-apteka.ru/catalog/kat/ripart-long-sr-vo-dzameshch-sinov-jidk-20mgml-2ml-shpric-n1-ingal-70_32534640/",
    "https://belgorod.social-apteka.ru/catalog/bolezni-sustavov/ripart-long-sr-vo-dzameshch-sinovialnoy-jidkosti-20mgml-shpric-3ml-n1-rossiya-18_71697/",
    "https://belgorod.social-apteka.ru/catalog/kat/ripart-forte-sr-vo-dlya-zameshcheniya-sinovialnoy-jidkosti-15mgml-shpric-3ml-100_34077342/",
    "https://belgorod.social-apteka.ru/catalog/bolezni-sustavov/rumalon-amp-1ml-n10-39_24853/",
    "https://belgorod.social-apteka.ru/catalog/gomeopatiya/traumel-s-amp-22ml-n5-44_11979/",
    "https://belgorod.social-apteka.ru/catalog/bolezni-sustavov/fermatron-shpric-1-2ml-n1-77_33430/",
    "https://belgorod.social-apteka.ru/catalog/bolezni-sustavov/fermatron-shpric-15-2ml-n1-38_34995/",
    "https://belgorod.social-apteka.ru/catalog/kat/fleksotron-kross-implantant-din-60mg3ml-sayvijn-bayotek-6_32534636/",
    "https://belgorod.social-apteka.ru/catalog/kat/fleksotron-solo-implant-din-22-22mgml-2ml-sistema-plyus-20_33579271/",
    "https://belgorod.social-apteka.ru/catalog/kat/fleksotron-ultra-implant-din-25-25mgml-48ml-albomed-63_33593771/",
    "https://belgorod.social-apteka.ru/catalog/kat/hronotron-implantat-inekc-gel-dlya-vsust-vved-20mgml-2ml-n1-mastelli-61_33593758/",
    "https://volgograd.social-apteka.ru/catalog/bolezni-sustavov/ameloteks-r-r-d-in-1-5ml-n5-soteks_33449/",
    "https://volgograd.social-apteka.ru/catalog/bolezni-sustavov/armaviskon-r-r-dvnutrisust-vved-2ml-2_1549818/",
    "https://volgograd.social-apteka.ru/catalog/bolezni-sustavov/armaviskon-plyus-r-r-dvnutrisust-vved-2ml-86_1549819/",
    "https://volgograd.social-apteka.ru/catalog/bolezni-sustavov/armaviskon-forte-r-r-dvnutrisust-vved-shpric-3ml-53_29463/",
    "https://volgograd.social-apteka.ru/catalog/kat/armaviskon-hondro-protez-sinovialnoy-jidkosti-3ml-n1-groteks-7_34113316/",
    "https://volgograd.social-apteka.ru/catalog/bolezni-sustavov/artogistan-r-r-din-100mgml-2ml-n10-41_28657/",
    "https://volgograd.social-apteka.ru/catalog/bolezni-sustavov/genitron-r-r-din-10mgml-15ml-n5-74_27287/",
    "https://volgograd.social-apteka.ru/catalog/bolezni-sustavov/gialurom-r-r-vsustav-shpric-15-2ml-n1-90_38239/",
    "https://volgograd.social-apteka.ru/catalog/bolezni-sustavov/gialurom-cs-vsustav-shpric-15-3ml-n1-10_23499/",
    "https://volgograd.social-apteka.ru/search_to_go/?q=%D0%94%D1%8C%D1%8E%D1%80%D0%B0%D0%BB%D0%B0%D0%BD",
    "https://volgograd.social-apteka.ru/catalog/bolezni-sustavov/inektran-r-r-din-100mgml-2ml-n10-95_27204/",
    "https://volgograd.social-apteka.ru/catalog/protivovospalitelnye-sredstva-dlya-oporno-dvigatelnogo-apparata/meloksikam-r-r-din-10mgml-15ml-n5-100_8389805/",
    "https://volgograd.social-apteka.ru/catalog/obezbolivayushchie/movalis-amp-15mg-15ml-n5-67_20078/",
    "https://volgograd.social-apteka.ru/catalog/bolezni-sustavov/mukosat-amp-10-1ml-n10-84_16578/",
    "https://volgograd.social-apteka.ru/catalog/kat/osteokoll-implantat-kollagen-d-periartikulyarnogo-vved-2ml-n5-guna-70_34085377/",
    "https://volgograd.social-apteka.ru/catalog/kat/pleksatron-kollagen-dvnutrisustav-i-periart-vved-2ml-n5-guna-96_34077275/",
    "https://volgograd.social-apteka.ru/catalog/kat/ripart-long-sr-vo-dzameshch-sinov-jidk-20mgml-2ml-shpric-n1-ingal-70_32534640/",
    "https://volgograd.social-apteka.ru/catalog/bolezni-sustavov/ripart-long-sr-vo-dzameshch-sinovialnoy-jidkosti-20mgml-shpric-3ml-n1-rossiya-18_71697/",
    "https://volgograd.social-apteka.ru/catalog/kat/ripart-forte-sr-vo-dlya-zameshcheniya-sinovialnoy-jidkosti-15mgml-shpric-3ml-100_34077342/",
    "https://volgograd.social-apteka.ru/catalog/bolezni-sustavov/rumalon-amp-1ml-n10-39_24853/",
    "https://volgograd.social-apteka.ru/catalog/gomeopatiya/traumel-s-amp-22ml-n5-44_11979/",
    "https://volgograd.social-apteka.ru/catalog/bolezni-sustavov/fermatron-shpric-1-2ml-n1-77_33430/",
    "https://volgograd.social-apteka.ru/catalog/bolezni-sustavov/fermatron-shpric-15-2ml-n1-38_34995/",
    "https://volgograd.social-apteka.ru/catalog/kat/fleksotron-kross-implantant-din-60mg3ml-sayvijn-bayotek-6_32534636/",
    "https://volgograd.social-apteka.ru/catalog/kat/fleksotron-solo-implant-din-22-22mgml-2ml-sistema-plyus-20_33579271/",
    "https://volgograd.social-apteka.ru/catalog/kat/fleksotron-ultra-implant-din-25-25mgml-48ml-albomed-63_33593771/",
    "https://volgograd.social-apteka.ru/catalog/kat/hronotron-implantat-inekc-gel-dlya-vsust-vved-20mgml-2ml-n1-mastelli-61_33593758/",
    "https://voronezh.social-apteka.ru/catalog/bolezni-sustavov/ameloteks-r-r-d-in-1-5ml-n5-soteks_33449/",
    "https://voronezh.social-apteka.ru/catalog/bolezni-sustavov/armaviskon-r-r-dvnutrisust-vved-2ml-2_1549818/",
    "https://voronezh.social-apteka.ru/catalog/bolezni-sustavov/armaviskon-plyus-r-r-dvnutrisust-vved-2ml-86_1549819/",
    "https://voronezh.social-apteka.ru/catalog/bolezni-sustavov/armaviskon-forte-r-r-dvnutrisust-vved-shpric-3ml-53_29463/",
    "https://voronezh.social-apteka.ru/catalog/kat/armaviskon-hondro-protez-sinovialnoy-jidkosti-3ml-n1-groteks-7_34113316/",
    "https://voronezh.social-apteka.ru/catalog/bolezni-sustavov/artogistan-r-r-din-100mgml-2ml-n10-41_28657/",
    "https://voronezh.social-apteka.ru/catalog/bolezni-sustavov/genitron-r-r-din-10mgml-15ml-n5-74_27287/",
    "https://voronezh.social-apteka.ru/catalog/bolezni-sustavov/gialurom-r-r-vsustav-shpric-15-2ml-n1-90_38239/",
    "https://voronezh.social-apteka.ru/catalog/bolezni-sustavov/gialurom-cs-vsustav-shpric-15-3ml-n1-10_23499/",
    "https://voronezh.social-apteka.ru/search_to_go/?q=%D0%94%D1%8C%D1%8E%D1%80%D0%B0%D0%BB%D0%B0%D0%BD",
    "https://voronezh.social-apteka.ru/catalog/bolezni-sustavov/inektran-r-r-din-100mgml-2ml-n10-95_27204/",
    "https://voronezh.social-apteka.ru/catalog/protivovospalitelnye-sredstva-dlya-oporno-dvigatelnogo-apparata/meloksikam-r-r-din-10mgml-15ml-n5-100_8389805/",
    "https://voronezh.social-apteka.ru/catalog/obezbolivayushchie/movalis-amp-15mg-15ml-n5-67_20078/",
    "https://voronezh.social-apteka.ru/catalog/bolezni-sustavov/mukosat-amp-10-1ml-n10-84_16578/",
    "https://voronezh.social-apteka.ru/catalog/kat/osteokoll-implantat-kollagen-d-periartikulyarnogo-vved-2ml-n5-guna-70_34085377/",
    "https://voronezh.social-apteka.ru/catalog/kat/pleksatron-kollagen-dvnutrisustav-i-periart-vved-2ml-n5-guna-96_34077275/",
    "https://voronezh.social-apteka.ru/catalog/kat/ripart-long-sr-vo-dzameshch-sinov-jidk-20mgml-2ml-shpric-n1-ingal-70_32534640/",
    "https://voronezh.social-apteka.ru/catalog/bolezni-sustavov/ripart-long-sr-vo-dzameshch-sinovialnoy-jidkosti-20mgml-shpric-3ml-n1-rossiya-18_71697/",
    "https://voronezh.social-apteka.ru/catalog/kat/ripart-forte-sr-vo-dlya-zameshcheniya-sinovialnoy-jidkosti-15mgml-shpric-3ml-100_34077342/",
    "https://voronezh.social-apteka.ru/catalog/bolezni-sustavov/rumalon-amp-1ml-n10-39_24853/",
    "https://voronezh.social-apteka.ru/catalog/gomeopatiya/traumel-s-amp-22ml-n5-44_11979/",
    "https://voronezh.social-apteka.ru/catalog/bolezni-sustavov/fermatron-shpric-1-2ml-n1-77_33430/",
    "https://voronezh.social-apteka.ru/catalog/bolezni-sustavov/fermatron-shpric-15-2ml-n1-38_34995/",
    "https://voronezh.social-apteka.ru/catalog/kat/fleksotron-kross-implantant-din-60mg3ml-sayvijn-bayotek-6_32534636/",
    "https://voronezh.social-apteka.ru/catalog/kat/fleksotron-solo-implant-din-22-22mgml-2ml-sistema-plyus-20_33579271/",
    "https://voronezh.social-apteka.ru/catalog/kat/fleksotron-ultra-implant-din-25-25mgml-48ml-albomed-63_33593771/",
    "https://voronezh.social-apteka.ru/catalog/kat/hronotron-implantat-inekc-gel-dlya-vsust-vved-20mgml-2ml-n1-mastelli-61_33593758/",
    "https://lipeck.social-apteka.ru/catalog/bolezni-sustavov/ameloteks-r-r-d-in-1-5ml-n5-soteks_33449/",
    "https://lipeck.social-apteka.ru/catalog/bolezni-sustavov/armaviskon-r-r-dvnutrisust-vved-2ml-2_1549818/",
    "https://lipeck.social-apteka.ru/catalog/bolezni-sustavov/armaviskon-plyus-r-r-dvnutrisust-vved-2ml-86_1549819/",
    "https://lipeck.social-apteka.ru/catalog/bolezni-sustavov/armaviskon-forte-r-r-dvnutrisust-vved-shpric-3ml-53_29463/",
    "https://lipeck.social-apteka.ru/catalog/kat/armaviskon-hondro-protez-sinovialnoy-jidkosti-3ml-n1-groteks-7_34113316/",
    "https://lipeck.social-apteka.ru/catalog/bolezni-sustavov/artogistan-r-r-din-100mgml-2ml-n10-41_28657/",
    "https://lipeck.social-apteka.ru/catalog/bolezni-sustavov/genitron-r-r-din-10mgml-15ml-n5-74_27287/",
    "https://lipeck.social-apteka.ru/catalog/bolezni-sustavov/gialurom-r-r-vsustav-shpric-15-2ml-n1-90_38239/",
    "https://lipeck.social-apteka.ru/catalog/bolezni-sustavov/gialurom-cs-vsustav-shpric-15-3ml-n1-10_23499/",
    "https://lipeck.social-apteka.ru/search_to_go/?q=%D0%94%D1%8C%D1%8E%D1%80%D0%B0%D0%BB%D0%B0%D0%BD",
    "https://lipeck.social-apteka.ru/catalog/bolezni-sustavov/inektran-r-r-din-100mgml-2ml-n10-95_27204/",
    "https://lipeck.social-apteka.ru/catalog/protivovospalitelnye-sredstva-dlya-oporno-dvigatelnogo-apparata/meloksikam-r-r-din-10mgml-15ml-n5-100_8389805/",
    "https://lipeck.social-apteka.ru/catalog/obezbolivayushchie/movalis-amp-15mg-15ml-n5-67_20078/",
    "https://lipeck.social-apteka.ru/catalog/bolezni-sustavov/mukosat-amp-10-1ml-n10-84_16578/",
    "https://lipeck.social-apteka.ru/catalog/kat/osteokoll-implantat-kollagen-d-periartikulyarnogo-vved-2ml-n5-guna-70_34085377/",
    "https://lipeck.social-apteka.ru/catalog/kat/pleksatron-kollagen-dvnutrisustav-i-periart-vved-2ml-n5-guna-96_34077275/",
    "https://lipeck.social-apteka.ru/catalog/kat/ripart-long-sr-vo-dzameshch-sinov-jidk-20mgml-2ml-shpric-n1-ingal-70_32534640/",
    "https://lipeck.social-apteka.ru/catalog/bolezni-sustavov/ripart-long-sr-vo-dzameshch-sinovialnoy-jidkosti-20mgml-shpric-3ml-n1-rossiya-18_71697/",
    "https://lipeck.social-apteka.ru/catalog/kat/ripart-forte-sr-vo-dlya-zameshcheniya-sinovialnoy-jidkosti-15mgml-shpric-3ml-100_34077342/",
    "https://lipeck.social-apteka.ru/catalog/bolezni-sustavov/rumalon-amp-1ml-n10-39_24853/",
    "https://lipeck.social-apteka.ru/catalog/gomeopatiya/traumel-s-amp-22ml-n5-44_11979/",
    "https://lipeck.social-apteka.ru/catalog/bolezni-sustavov/fermatron-shpric-1-2ml-n1-77_33430/",
    "https://lipeck.social-apteka.ru/catalog/bolezni-sustavov/fermatron-shpric-15-2ml-n1-38_34995/",
    "https://lipeck.social-apteka.ru/catalog/kat/fleksotron-kross-implantant-din-60mg3ml-sayvijn-bayotek-6_32534636/",
    "https://lipeck.social-apteka.ru/catalog/kat/fleksotron-solo-implant-din-22-22mgml-2ml-sistema-plyus-20_33579271/",
    "https://lipeck.social-apteka.ru/catalog/kat/fleksotron-ultra-implant-din-25-25mgml-48ml-albomed-63_33593771/",
    "https://lipeck.social-apteka.ru/catalog/kat/hronotron-implantat-inekc-gel-dlya-vsust-vved-20mgml-2ml-n1-mastelli-61_33593758/",
    "https://krasnodar.social-apteka.ru/catalog/bolezni-sustavov/ameloteks-r-r-d-in-1-5ml-n5-soteks_33449/",
    "https://krasnodar.social-apteka.ru/catalog/bolezni-sustavov/armaviskon-r-r-dvnutrisust-vved-2ml-2_1549818/",
    "https://krasnodar.social-apteka.ru/catalog/bolezni-sustavov/armaviskon-plyus-r-r-dvnutrisust-vved-2ml-86_1549819/",
    "https://krasnodar.social-apteka.ru/catalog/bolezni-sustavov/armaviskon-forte-r-r-dvnutrisust-vved-shpric-3ml-53_29463/",
    "https://krasnodar.social-apteka.ru/catalog/kat/armaviskon-hondro-protez-sinovialnoy-jidkosti-3ml-n1-groteks-7_34113316/",
    "https://krasnodar.social-apteka.ru/catalog/bolezni-sustavov/artogistan-r-r-din-100mgml-2ml-n10-41_28657/",
    "https://krasnodar.social-apteka.ru/catalog/bolezni-sustavov/genitron-r-r-din-10mgml-15ml-n5-74_27287/",
    "https://krasnodar.social-apteka.ru/catalog/bolezni-sustavov/gialurom-r-r-vsustav-shpric-15-2ml-n1-90_38239/",
    "https://krasnodar.social-apteka.ru/catalog/bolezni-sustavov/gialurom-cs-vsustav-shpric-15-3ml-n1-10_23499/",
    "https://krasnodar.social-apteka.ru/search_to_go/?q=%D0%94%D1%8C%D1%8E%D1%80%D0%B0%D0%BB%D0%B0%D0%BD",
    "https://krasnodar.social-apteka.ru/catalog/bolezni-sustavov/inektran-r-r-din-100mgml-2ml-n10-95_27204/",
    "https://krasnodar.social-apteka.ru/catalog/protivovospalitelnye-sredstva-dlya-oporno-dvigatelnogo-apparata/meloksikam-r-r-din-10mgml-15ml-n5-100_8389805/",
    "https://krasnodar.social-apteka.ru/catalog/obezbolivayushchie/movalis-amp-15mg-15ml-n5-67_20078/",
    "https://krasnodar.social-apteka.ru/catalog/bolezni-sustavov/mukosat-amp-10-1ml-n10-84_16578/",
    "https://krasnodar.social-apteka.ru/catalog/kat/osteokoll-implantat-kollagen-d-periartikulyarnogo-vved-2ml-n5-guna-70_34085377/",
    "https://krasnodar.social-apteka.ru/catalog/kat/pleksatron-kollagen-dvnutrisustav-i-periart-vved-2ml-n5-guna-96_34077275/",
    "https://krasnodar.social-apteka.ru/catalog/kat/ripart-long-sr-vo-dzameshch-sinov-jidk-20mgml-2ml-shpric-n1-ingal-70_32534640/",
    "https://krasnodar.social-apteka.ru/catalog/bolezni-sustavov/ripart-long-sr-vo-dzameshch-sinovialnoy-jidkosti-20mgml-shpric-3ml-n1-rossiya-18_71697/",
    "https://krasnodar.social-apteka.ru/catalog/kat/ripart-forte-sr-vo-dlya-zameshcheniya-sinovialnoy-jidkosti-15mgml-shpric-3ml-100_34077342/",
    "https://krasnodar.social-apteka.ru/catalog/bolezni-sustavov/rumalon-amp-1ml-n10-39_24853/",
    "https://krasnodar.social-apteka.ru/catalog/gomeopatiya/traumel-s-amp-22ml-n5-44_11979/",
    "https://krasnodar.social-apteka.ru/catalog/bolezni-sustavov/fermatron-shpric-1-2ml-n1-77_33430/",
    "https://krasnodar.social-apteka.ru/catalog/bolezni-sustavov/fermatron-shpric-15-2ml-n1-38_34995/",
    "https://krasnodar.social-apteka.ru/catalog/kat/fleksotron-kross-implantant-din-60mg3ml-sayvijn-bayotek-6_32534636/",
    "https://krasnodar.social-apteka.ru/catalog/kat/fleksotron-solo-implant-din-22-22mgml-2ml-sistema-plyus-20_33579271/",
    "https://krasnodar.social-apteka.ru/catalog/kat/fleksotron-ultra-implant-din-25-25mgml-48ml-albomed-63_33593771/",
    "https://krasnodar.social-apteka.ru/catalog/kat/hronotron-implantat-inekc-gel-dlya-vsust-vved-20mgml-2ml-n1-mastelli-61_33593758/",
    "https://majkop.social-apteka.ru/catalog/bolezni-sustavov/ameloteks-r-r-d-in-1-5ml-n5-soteks_33449/",
    "https://majkop.social-apteka.ru/catalog/bolezni-sustavov/armaviskon-r-r-dvnutrisust-vved-2ml-2_1549818/",
    "https://majkop.social-apteka.ru/catalog/bolezni-sustavov/armaviskon-plyus-r-r-dvnutrisust-vved-2ml-86_1549819/",
    "https://majkop.social-apteka.ru/catalog/bolezni-sustavov/armaviskon-forte-r-r-dvnutrisust-vved-shpric-3ml-53_29463/",
    "https://majkop.social-apteka.ru/catalog/kat/armaviskon-hondro-protez-sinovialnoy-jidkosti-3ml-n1-groteks-7_34113316/",
    "https://majkop.social-apteka.ru/catalog/bolezni-sustavov/artogistan-r-r-din-100mgml-2ml-n10-41_28657/",
    "https://majkop.social-apteka.ru/catalog/bolezni-sustavov/genitron-r-r-din-10mgml-15ml-n5-74_27287/",
    "https://majkop.social-apteka.ru/catalog/bolezni-sustavov/gialurom-r-r-vsustav-shpric-15-2ml-n1-90_38239/",
    "https://majkop.social-apteka.ru/catalog/bolezni-sustavov/gialurom-cs-vsustav-shpric-15-3ml-n1-10_23499/",
    "https://majkop.social-apteka.ru/search_to_go/?q=%D0%94%D1%8C%D1%8E%D1%80%D0%B0%D0%BB%D0%B0%D0%BD",
    "https://majkop.social-apteka.ru/catalog/bolezni-sustavov/inektran-r-r-din-100mgml-2ml-n10-95_27204/",
    "https://majkop.social-apteka.ru/catalog/protivovospalitelnye-sredstva-dlya-oporno-dvigatelnogo-apparata/meloksikam-r-r-din-10mgml-15ml-n5-100_8389805/",
    "https://majkop.social-apteka.ru/catalog/obezbolivayushchie/movalis-amp-15mg-15ml-n5-67_20078/",
    "https://majkop.social-apteka.ru/catalog/bolezni-sustavov/mukosat-amp-10-1ml-n10-84_16578/",
    "https://majkop.social-apteka.ru/catalog/kat/osteokoll-implantat-kollagen-d-periartikulyarnogo-vved-2ml-n5-guna-70_34085377/",
    "https://majkop.social-apteka.ru/catalog/kat/pleksatron-kollagen-dvnutrisustav-i-periart-vved-2ml-n5-guna-96_34077275/",
    "https://majkop.social-apteka.ru/catalog/kat/ripart-long-sr-vo-dzameshch-sinov-jidk-20mgml-2ml-shpric-n1-ingal-70_32534640/",
    "https://majkop.social-apteka.ru/catalog/bolezni-sustavov/ripart-long-sr-vo-dzameshch-sinovialnoy-jidkosti-20mgml-shpric-3ml-n1-rossiya-18_71697/",
    "https://majkop.social-apteka.ru/catalog/kat/ripart-forte-sr-vo-dlya-zameshcheniya-sinovialnoy-jidkosti-15mgml-shpric-3ml-100_34077342/",
    "https://majkop.social-apteka.ru/catalog/bolezni-sustavov/rumalon-amp-1ml-n10-39_24853/",
    "https://majkop.social-apteka.ru/catalog/gomeopatiya/traumel-s-amp-22ml-n5-44_11979/",
    "https://majkop.social-apteka.ru/catalog/bolezni-sustavov/fermatron-shpric-1-2ml-n1-77_33430/",
    "https://majkop.social-apteka.ru/catalog/bolezni-sustavov/fermatron-shpric-15-2ml-n1-38_34995/",
    "https://majkop.social-apteka.ru/catalog/kat/fleksotron-kross-implantant-din-60mg3ml-sayvijn-bayotek-6_32534636/",
    "https://majkop.social-apteka.ru/catalog/kat/fleksotron-solo-implant-din-22-22mgml-2ml-sistema-plyus-20_33579271/",
    "https://majkop.social-apteka.ru/catalog/kat/fleksotron-ultra-implant-din-25-25mgml-48ml-albomed-63_33593771/",
    "https://majkop.social-apteka.ru/catalog/kat/hronotron-implantat-inekc-gel-dlya-vsust-vved-20mgml-2ml-n1-mastelli-61_33593758/",
    "https://stavropol.social-apteka.ru/catalog/bolezni-sustavov/ameloteks-r-r-d-in-1-5ml-n5-soteks_33449/",
    "https://stavropol.social-apteka.ru/catalog/bolezni-sustavov/armaviskon-r-r-dvnutrisust-vved-2ml-2_1549818/",
    "https://stavropol.social-apteka.ru/catalog/bolezni-sustavov/armaviskon-plyus-r-r-dvnutrisust-vved-2ml-86_1549819/",
    "https://stavropol.social-apteka.ru/catalog/bolezni-sustavov/armaviskon-forte-r-r-dvnutrisust-vved-shpric-3ml-53_29463/",
    "https://stavropol.social-apteka.ru/catalog/kat/armaviskon-hondro-protez-sinovialnoy-jidkosti-3ml-n1-groteks-7_34113316/",
    "https://stavropol.social-apteka.ru/catalog/bolezni-sustavov/artogistan-r-r-din-100mgml-2ml-n10-41_28657/",
    "https://stavropol.social-apteka.ru/catalog/bolezni-sustavov/genitron-r-r-din-10mgml-15ml-n5-74_27287/",
    "https://stavropol.social-apteka.ru/catalog/bolezni-sustavov/gialurom-r-r-vsustav-shpric-15-2ml-n1-90_38239/",
    "https://stavropol.social-apteka.ru/catalog/bolezni-sustavov/gialurom-cs-vsustav-shpric-15-3ml-n1-10_23499/",
    "https://stavropol.social-apteka.ru/search_to_go/?q=%D0%94%D1%8C%D1%8E%D1%80%D0%B0%D0%BB%D0%B0%D0%BD",
    "https://stavropol.social-apteka.ru/catalog/bolezni-sustavov/inektran-r-r-din-100mgml-2ml-n10-95_27204/",
    "https://stavropol.social-apteka.ru/catalog/protivovospalitelnye-sredstva-dlya-oporno-dvigatelnogo-apparata/meloksikam-r-r-din-10mgml-15ml-n5-100_8389805/",
    "https://stavropol.social-apteka.ru/catalog/obezbolivayushchie/movalis-amp-15mg-15ml-n5-67_20078/",
    "https://stavropol.social-apteka.ru/catalog/bolezni-sustavov/mukosat-amp-10-1ml-n10-84_16578/",
    "https://stavropol.social-apteka.ru/catalog/kat/osteokoll-implantat-kollagen-d-periartikulyarnogo-vved-2ml-n5-guna-70_34085377/",
    "https://stavropol.social-apteka.ru/catalog/kat/pleksatron-kollagen-dvnutrisustav-i-periart-vved-2ml-n5-guna-96_34077275/",
    "https://stavropol.social-apteka.ru/catalog/kat/ripart-long-sr-vo-dzameshch-sinov-jidk-20mgml-2ml-shpric-n1-ingal-70_32534640/",
    "https://stavropol.social-apteka.ru/catalog/bolezni-sustavov/ripart-long-sr-vo-dzameshch-sinovialnoy-jidkosti-20mgml-shpric-3ml-n1-rossiya-18_71697/",
    "https://stavropol.social-apteka.ru/catalog/kat/ripart-forte-sr-vo-dlya-zameshcheniya-sinovialnoy-jidkosti-15mgml-shpric-3ml-100_34077342/",
    "https://stavropol.social-apteka.ru/catalog/bolezni-sustavov/rumalon-amp-1ml-n10-39_24853/",
    "https://stavropol.social-apteka.ru/catalog/gomeopatiya/traumel-s-amp-22ml-n5-44_11979/",
    "https://stavropol.social-apteka.ru/catalog/bolezni-sustavov/fermatron-shpric-1-2ml-n1-77_33430/",
    "https://stavropol.social-apteka.ru/catalog/bolezni-sustavov/fermatron-shpric-15-2ml-n1-38_34995/",
    "https://stavropol.social-apteka.ru/catalog/kat/fleksotron-kross-implantant-din-60mg3ml-sayvijn-bayotek-6_32534636/",
    "https://stavropol.social-apteka.ru/catalog/kat/fleksotron-solo-implant-din-22-22mgml-2ml-sistema-plyus-20_33579271/",
    "https://stavropol.social-apteka.ru/catalog/kat/fleksotron-ultra-implant-din-25-25mgml-48ml-albomed-63_33593771/",
    "https://stavropol.social-apteka.ru/catalog/kat/hronotron-implantat-inekc-gel-dlya-vsust-vved-20mgml-2ml-n1-mastelli-61_33593758/"]
pages = {}
prep = []
for i in range(len(linklist)):
    respone = requests.get(linklist[i])
    html = respone.text
    print(i)

    soup = BeautifulSoup(html, 'html.parser')
    items = soup.find_all("body")
    if not items:
        print("не туда")

    try:
        for item in items:
            prep.append(
                {
                    'title': item.find("h1", id="brand").text.strip(),
                    'price': item.find("span", class_="product-order__price").text.replace(' ', ''),
                    'link': linklist[i],
                    'city': item.find('a', class_='vr-template__link').text.strip()
                }
            )
    except:
        print("")

print(prep)

with open(rf"C:\Users\danil\OneDrive\Документы\Python\Аптечка\Результаты парсинга\SocialApteka_{date}.csv", 'a', newline='', encoding='utf-8') as file:
    writer = csv.writer(file, delimiter=';')
    writer.writerow(
        ['Дата', 'Наименование препарата как у нас', 'Наименование препарата как у аптеки', 'Наименование АС',
         'Ссылка на препарат', 'Город', 'Цена'])
    for item in prep:
        writer.writerow([date, '', item['title'], name, item['link'], item["city"], item['price']])